/**
 * Browser smoke test: proves onnxruntime-web actually initializes and runs a
 * real (tiny) ONNX graph in the target environment. The fixture
 * `src/__fixtures__/add.onnx` is a single Add op (float32 [1] inputs a + b,
 * opset 18), generated by scripts/make-fixture.py and committed.
 */
import * as ort from 'onnxruntime-web';
import { describe, expect, it } from 'vitest';
import addModelUrl from './__fixtures__/add.onnx?url';

// Deterministic single-thread WASM: no COOP/COEP requirement in the test server.
ort.env.wasm.numThreads = 1;

// Structural view of WebGPU (lib.dom has no navigator.gpu typing).
const gpu = (
  globalThis.navigator as unknown as
    | { gpu?: { requestAdapter(): Promise<object | null> } }
    | undefined
)?.gpu;

async function fetchFixture(): Promise<Uint8Array> {
  const res = await fetch(addModelUrl);
  if (!res.ok) throw new Error(`failed to fetch fixture: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

async function runAdd(session: ort.InferenceSession): Promise<number> {
  const feeds = {
    a: new ort.Tensor('float32', Float32Array.from([1]), [1]),
    b: new ort.Tensor('float32', Float32Array.from([2]), [1]),
  };
  const results = await session.run(feeds);
  const c = results['c'];
  if (!c) throw new Error('missing output c');
  return (c.data as Float32Array)[0] ?? Number.NaN;
}

describe('onnxruntime-web in the browser', () => {
  it('runs 1 + 2 = 3 on the wasm execution provider', async () => {
    const bytes = await fetchFixture();
    const session = await ort.InferenceSession.create(bytes, {
      executionProviders: ['wasm'],
    });
    try {
      expect(await runAdd(session)).toBe(3);
      console.log('[ort.browser.test] EP ran: wasm');
    } finally {
      await session.release();
    }
  });

  // Never fails on a missing adapter: skipped without navigator.gpu, and a
  // denied adapter / EP init failure downgrades to a logged wasm-only pass.
  it.skipIf(!gpu)(
    'runs 1 + 2 = 3 on the webgpu execution provider when an adapter exists',
    async () => {
      const adapter = await gpu!.requestAdapter().catch(() => null);
      if (!adapter) {
        console.log('[ort.browser.test] EP ran: none (navigator.gpu present but no adapter)');
        return;
      }
      const bytes = await fetchFixture();
      let session: ort.InferenceSession;
      try {
        session = await ort.InferenceSession.create(bytes, {
          executionProviders: ['webgpu'],
        });
      } catch (err) {
        // Adapter exists but the EP could not initialize (e.g. headless
        // driver quirks) — log and soft-pass rather than flake CI.
        console.log('[ort.browser.test] EP ran: none (webgpu init failed)', err);
        return;
      }
      try {
        expect(await runAdd(session)).toBe(3);
        console.log('[ort.browser.test] EP ran: webgpu');
      } finally {
        await session.release();
      }
    },
  );
});
